In [1]:
import cv2

In [ ]:
# sudo apt-get install pkg-config
# pkg-config --modversion opencv
# sudo apt-get install build-essential cmake
# sudo apt-get install freeglut3 freeglut3-dev
# sudo apt-get install glew-utils glee-dev
# sudo apt-get install libglew-dev
# sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev
# sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libxvidcore-dev libx264-dev libxine2-dev
# sudo apt-get install libv4l-dev v4l-utils
# sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
# sudo apt-get install libgtk2.0-dev
# sudo apt-get install mesa-utils libgl1-mesa-dri libgtkgl2.0-dev libgtkglext1-dev
# sudo apt-get install libatlas-base-dev gfortran libeigen3-dev

In [ ]:
# cd ~
# cd sw/
# mkdir opencv
# cd opencv
# wget -O opencv.zip https://github.com/opencv/opencv/archive/4.2.0.zip
# unzip opencv.zip

In [ ]:
# wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.2.0.zip
# unzip opencv_contrib.zip

In [ ]:
# cd opencv-4.2.0/
# mkdir build
# cd buil

In [ ]:
# 아나콘다 환경 설정 잠시 정지시킴
# sudo apt-get install python2.7-dev python3-dev python-numpy python3-numpy

In [ ]:

# /home/bitai/anaconda3/bin/python

In [ ]:
# 아나콘다 경로를 잘 파악하고 있다면 문제 없음
# cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=OFF -D WITH_IPP=OFF -D 
WITH_1394=OFF -D BUILD_WITH_DEBUG_INFO=OFF -D BUILD_DOCS=OFF -D INSTALL_C_EXAMPLES=ON -D 
INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D WITH_QT=OFF -D 
WITH_GTK=ON -D WITH_OPENGL=ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.2.0/modules -D WITH_V4L=ON -D
WITH_FFMPEG=ON -D WITH_XINE=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D OPENCV_GENERATE_PKGCONFIG=ON ../

In [ ]:
# 아나콘다상의 파이썬 경로를 파악하지 못한다면 아래 방식으로
# cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=OFF -D WITH_IPP=OFF -D 
WITH_1394=OFF -D BUILD_WITH_DEBUG_INFO=OFF -D BUILD_DOCS=OFF -D INSTALL_C_EXAMPLES=ON -D 
INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D WITH_QT=OFF -D 
WITH_GTK=ON -D WITH_OPENGL=ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.2.0/modules -D WITH_V4L=ON -D 
WITH_FFMPEG=ON -D WITH_XINE=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D OPENCV_GENERATE_PKGCONFIG=ON -D 
PYTHON3_INCLUDE_DIR=/home/bitai/anaconda3/include/python3.7m/ -D 
PYTHON3_NUMPY_INCLUDE_DIRS=/home/bitai/anaconda3/lib/python3.7/site-packages/numpy/core/include/ -D
PYTHON3_PACKAGES_PATH=/home/bitai/anaconda3/lib/python3.7/site-packages -D PYTHON3_LIBRARY=/home/bitai/anaconda3/
lib/libpython3.7m.so ../

In [ ]:
# cat /proc/cpuinfo | grep processor | wc -l
# time make -j12

In [ ]:
# sudo make install

In [ ]:
# cat /etc/ld.so.conf.d/*
# sudo ldconfig

In [ ]:
# cd ~/proj/
# mkdir test
# cd test
# g++ -o facedetect /usr/local/share/opencv4/samples/cpp/facedetect.cpp $(pkg-config opencv4 --libs --cflags)
# ./facedetect --cascade="/usr/local/share/opencv4/haarcascades/haarcascade_frontalface_alt.xml
" --nested-cascade="/usr/local/share/opencv4/haarcascades/haarcascade_eye_tree_eyeglasses.xml" --scale=1.3

In [ ]:
# 아나콘다 설정 다시 활성화

In [ ]:
!pip install opencv-python

In [ ]:
# 그래픽 카드는 이미지 처리 시 메모리 복사가 일어나는데 메모리는 3번째로 느리므로(레지스터>캐시메모리S>메모리D>I/O) 엄청 느려짐.


# CNN 딥신경망 분류 중 하나. 주로 컴퓨터 비전(대상을 보고 인식)이나 이미지 처리 분야에서 사용. -인식, 분류, 식별
# 이미지를 인식하고 각 이미지에 적합한 라벨을 붙이는 역할
# 입력레이어, 결과레이어, 숨김레이어(완전연결레이어, 합성곱레이어, 활성화함수 역할의 단일RELU레이어, 정규화레이어, 풀링레이어)
# CNN 아키텍처
# 1. 입력 이미지
# 2. 합성곱 레이어: 특성탐지기(행렬,패턴)을 사용해 특성맵(작은이미지)을 얻는다. conv2D
# 3. 풀링 레이어: 중요한 특성은 남기고 중요하지 않은 정보는 무시해 더 작은 이미지를 얻는다.(최대풀링-최대값픽, 최소풀링, 평균풀링) Maxpool2D
# 4. 플래트닝: 풀링된 특성맵(여러개)을 펴서 ANN 입력 형태인 하나의 열(행->열)로 만든다. Flatten()

# CNN 레이어 추가 시 Conv2D(32, 3, 3: 크기가 3x3인 특성탐지기 32개. 처음에는 32로 시작 후에 필요에 때라 64나 128로 늘려간다. 

In [ ]:
import cv2

In [2]:
print(cv2.__version__)

4.3.0


In [4]:
import numpy as np

In [6]:
img = np.random.randint(0, 10, (7, 7))

print(img)

[[6 5 4 4 3 1 2]
 [4 0 3 6 5 3 3]
 [3 7 3 9 4 9 9]
 [1 8 9 7 7 7 6]
 [5 2 3 0 9 0 1]
 [1 8 6 0 1 4 7]
 [7 3 6 9 6 3 5]]


In [8]:
img_np = np.ones([7, 7])

print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [9]:
kernel = np.array([-1, 0, 1])

print(kernel)

[-1  0  1]


In [11]:
print(type(kernel))
print(type(img_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
img_cv = cv2.resize(img_np, (7,7))

print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [14]:
kernel = cv2.resize(kernel, (1, 3))

print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [15]:
print(type(img_cv))
print(type(kernel))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [16]:
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3

# filter2D: Convlution이 라플라스 변환과 푸리에 변환을 가짐
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [ ]:
# sudo apt-get install ctags cscope

In [ ]:
# 라플라스 변환 => 전달 함수를 얻기 위해 계산
# 입력 대 출력비를 구하겠다.
# 입력이 10, 출력이 7, 입출력비: 7/10
# 입력이 y'' = y' +3y + 2
# 출력이 y' = 3e^3x => y = e^3x
# 라플라스 변환을 통해 상수로 만들 어 입출력비를 계산할 수 있게 된다.
# integral 0 ~ inf f(t)=e^-st dt

# 라플라스변환은 주어진 식을 간단한 식으로 변환한 뒤, 변형된 식을 풀고 그 해를 다시 원식으로 변환한다.
# 선형 동역학계와 같은 미분 방정식을 풀 때 유용하게 사용된다. 피에르시몽 라플라스의 이름을 따 붙여졌다.
# 라플라스 변환을 이용하면, 미분 방정식을 계수방정식으로 변환하여, 문제들을 쉽게 해결 할 수 있는 장점이 있다. 
# 초깃값 문제의 경우 일차적으로 일반해를 구하는 단계가 필요없게 되고, 비제차 미분방정식의 경우에는 대응하는 제차미분방정식을 먼저 풀 필요가 없다.

# 푸리에변환은 시간에 대한 함수(혹은 신호)를 함수를 구성하고 있는 주파수 성분으로 분해하는 작업이다.
# 시간의 영역에서의 미분연산은 주파수 영역에서 곱셈과 같아서, 미분방정식은 주파수 영역에서 더 쉽게 분석되기도 한다.
# 또한, 시간 영역에서의 합성곱 (convolution)은 주파수 영역에서 평범한 곱셈과 같다.
# 원하는 연산이 끝난 후에, 결과에 대한 변환으로 시간 영역으로의 돌아갈 수 있다. 


# Low Pass Filter(LPF 설계법) - ID Convolution
# 전달함수 -> 실제값을 필터링하는 방법

In [23]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [24]:
classifier = Sequential()
classifier.add(
    Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(Flatten())

In [25]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 30752)             0         
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [35]:
classifier.add(Dense(128, activation = 'relu'))
classifier.add(Dense(128, activation = 'relu'))
classifier.add(Dense(128, activation = 'relu'))
classifier.add(Dense(128, activation = 'relu'))
classifier.add(Dense(1, activation = 'softmax'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [36]:
from keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(rescale = 1. / 255, shear_range = 0.2, zoom_range = 0.2, horizontal_flip = True)

test_gen = ImageDataGenerator(rescale = 1.0 / 255)

In [28]:
!ls Applied-Deep-Learning-with-Keras/Lesson07

Activity13.ipynb  Datasets	    Exercise20.ipynb  Exercise22.ipynb
Activity14.ipynb  Exercise19.ipynb  Exercise21.ipynb


In [29]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets

 dataset  'test images'


In [30]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset

test_set  training_set


In [31]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/test_set

cats  dogs


In [32]:
!ls Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set

cats  dogs


In [37]:
trainSet = train_gen.flow_from_directory(
    'Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set',
    target_size = (64, 64), batch_size = 32, class_mode = 'binary')
testSet = test_gen.flow_from_directory('Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/test_set',
    target_size = (64, 64), batch_size = 32, class_mode = 'binary')

Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.


In [38]:
batch_size = 100

classifier.fit_generator(trainSet, steps_per_epoch = int(10000/batch_size), epochs = 2, validation_data = testSet,
    validation_steps = int(2500/batch_size))

Epoch 1/2
100/100 [==============================] - 43s 433ms/step - loss: 7.8057 - accuracy: 0.4881 - val_loss: 7.7009 - val_accuracy: 0.4950
Epoch 2/2
100/100 [==============================] - 38s 384ms/step - loss: 7.7914 - accuracy: 0.4891 - val_loss: 7.4912 - val_accuracy: 0.5088


In [39]:
import numpy as np

from keras.preprocessing import image

In [42]:
new_image = image.load_img('test_image_2.jpg', target_size = (64, 64))

In [43]:
new_image = image.img_to_array(new_image)
new_image = np.expand_dims(new_image, axis = 0)

result = classifier.predict(new_image)
#trainSet.class_indices

if result[0][0] == 1:
    prediction = 'Dog'
else:
    prediction = 'Cat'
    
print(prediction)

Dog
